config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @flat.restaurant = @restaurant
    if @flat.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def flat_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="big_container">
  <div class="banner">
    <p>Simple AirBnB</p>
    <p><%= link_to 'Add Flat', new_flat_path %></p>
  </div>

  <h1>All Flats</h1>

  <div class="container">

    <% @flats.each do |flat| %>
      <div class='card'>
        <img src="https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" class="image">
        <div class="text">
          <h2 id='name' ><%= flat.name %></h3>
          <p>Address: <%= flat.address %></p>
          <div class="icons">
            <p class="price"><i class="fas fa-dollar-sign"></i><%= flat.price_per_night %></p>
            <p><i class="fas fa-male"></i><%= flat.number_of_guests %></p>
          </div>
        </div>
        <div class="link">
          <%= link_to "More details", flat_path(flat) %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<p>more details</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/3b539bb7bb.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Muli&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>